import = ["/Users/gahanrakholia/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 15

[font.bold]
family = "IosevkaTermSlab Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTermSlab Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaTermSlab Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTermSlab Nerd Font"
style = "Regular"

[font.offset]
y = 6

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["-l", "-c", "tmux -u -f \"$XDG_CONFIG_HOME/tmux/tmux.conf\" attach || tmux -u -f \"$XDG_CONFIG_HOME/tmux/tmux.conf\""]
program = "/bin/zsh"

[window]
option_as_alt = "Both"
