#!/usr/bin/env zsh

is_dak_mode() {
    result=$(osascript -e 'tell application "System Events" to tell appearance preferences to get dark mode')
    [[ $result == "true" ]]
}

if is_dak_mode; then
    sed -i -e 's/catppuccin_latte.toml/catppuccin_mocha.toml/g' ~/.config/alacritty.toml
    sed -i -e 's/catppuccin-latte/catppuccin-mocha/g' ~/.config/k9s/config.yaml
    tmux setenv CATPPUCCIN_FLAVOR 'mocha'
    tmux set-option -g @catppuccin_flavor 'mocha'
else
    sed -i -e 's/catppuccin_mocha.toml/catppuccin_latte.toml/g' ~/.config/alacritty.toml
    sed -i -e 's/catppuccin-mocha/catppuccin-latte/g' ~/.config/k9s/config.yaml
    tmux setenv CATPPUCCIN_FLAVOR 'latte' 
    tmux set-option -g @catppuccin_flavor 'latte'
fi

