#!/usr/bin/env zsh

result=$(osascript -e 'tell application "System Events" to tell appearance preferences to get dark mode')

if [[ result == "true" ]]; then
    sed -i -e 's/catppuccin_latte.toml/catppuccin_mocha.toml/g' ~/.config/alacritty.toml
    tmux setenv CATPPUCCIN_FLAVOR 'mocha'
    tmux set-option -g @catppuccin_flavor 'mocha'
else
    sed -i -e 's/catppuccin_mocha.toml/catppuccin_latte.toml/g' ~/.config/alacritty.toml
    tmux setenv CATPPUCCIN_FLAVOR 'latte' 
    tmux set-option -g @catppuccin_flavor 'latte'
fi

