#!/usr/bin/env zsh

if [ "$(tmux display-message -p -F "#{session_name}")" = "popup" ];then
    tmux detach-client
else
    tmux -u popup -E "tmux -u attach -t popup || tmux -u new -c '#{pane_current_path}' -s popup"
fi
