#!/usr/bin/env python

from subprocess import check_output
import json
import re


class Connection:
    def __init__(self, id, name, status, is_connected):
        self.id = id
        self.name = name
        self.status = status if status == "Disconnected" or status == "Connecting" else "Connected"
        self.is_connected = is_connected

    def trimmed_name(self):
        match = re.search(".*(\((.*)\))", self.name)
        if match:
            return match.group(2)
        return self.name

    def tmux_status(self):
        return f"{self.trimmed_name()} {self.connection_indicator()}"

    def connection_indicator(self):
        match self.status:
            case "Disconnected":
                return "[✘]"
            case "Connecting":
                return "[⧖]"
            case _:
                return "[✓]"


output = check_output("pritunl-client list -j", shell=True)

conns = json.loads(output)
conns = map(lambda c: Connection(c["id"], c["name"], c["status"], c["connected"]), conns)
conns = map(lambda c: c.tmux_status(), conns)

tmux_preceeding_char = "#[align=right,bg=black,fg=colour242]#[bg=color242,fg=black]"

status = f"{tmux_preceeding_char} {'  '.join(conns)} #[align=right,bg=color242,fg=colour232]#[bg=colour232]🛡 "

print(status)
